import type { Metadata } from "next";
import "./globals.scss";
import { ClientGlobalproviders } from "./ClientGlobalProviders";

export const metadata: Metadata = {
  title: "MTG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientGlobalproviders>{children}</ClientGlobalproviders>
      </body>
    </html>
  );
}
